title: Karthik Sastry
logo: /assets/img/headshot-crop.jpg
description: "Prize Fellow in Economics, History, and Politics at Harvard University"
theme: jekyll-theme-minimal
url: https://ksastry.github.io
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
github:
  is_project_page: false
  is_user_page: false
author: Karthik Sastry